### ISSUE TITLE
I/O error in creating TAR

### ISSUE THREAD

**Issue by carande** [hudson3-plugins/backup-plugin#1]
I'm having an issue when I try to run the backup, it seems there is an I/O error in writing the tar.gz file.  I got a similar error when using zip.  I am using the "no-shutdown" mode.

```
[ INFO] Backup started at [01/05/15 11:30:49]
[ INFO] Full backup file name : /home/grouphigh/.hudson/backup/backup_20150105_1130.tar.gz
[ERROR] org.codehaus.plexus.archiver.ArchiverException: Problem creating TAR: Input/output error
org.jvnet.hudson.plugins.backup.BackupException: java.io.IOException: org.codehaus.plexus.archiver.ArchiverException: Problem creating TAR: Input/output error
    at org.jvnet.hudson.plugins.backup.utils.BackupEngine.doBackup(BackupEngine.java:115)
    at org.jvnet.hudson.plugins.backup.utils.BackupTask.run(BackupTask.java:130)
    at java.lang.Thread.run(Thread.java:722)
Caused by: java.io.IOException: org.codehaus.plexus.archiver.ArchiverException: Problem creating TAR: Input/output error
    at org.jvnet.hudson.plugins.backup.utils.BackupEngine.handleEnd(BackupEngine.java:104)
    at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:336)
    at org.jvnet.hudson.plugins.backup.utils.BackupEngine.doBackup(BackupEngine.java:113)
    ... 2 more
[ INFO] Cancel hudson shutdown mode
[ INFO] Backup end at [01/05/15 11:30:53]
[ INFO] [4.196s]
```

I checked the backup directory, and there is plenty of free disk space.

Any ideas how to fix this?

**Comment by carande** [comment]
Despite the error, I realized the backups were being created.  

However, since I want recurring backups, I'm using thinBackup instead now.  I do think the two plugins should be merged.
